#!/bin/sh

SCREENSHOTS=weblate_web/media/screenshots/
THUMBNAILS=weblate_web/media/thumbnails/

for file in $SCREENSHOTS*.png ; do
    base=${file##$SCREENSHOTS}
    thumb=$THUMBNAILS$base
    if [ ! -f $thumb ] ; then
        convert "$file" -resize 300x300^ -gravity center -crop 300x300+0+0 +repage "$thumb"
    fi
done
