# Generated by Django 2.1.4 on 2019-01-02 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0012_auto_20190102_1658'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(blank=True, max_length=200, verbose_name='Link text')),
                ('link_url', models.URLField(blank=True, verbose_name='Link URL')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField()),
                ('active', models.BooleanField(blank=True, db_index=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recurring', models.CharField(blank=True, choices=[('y', 'Annual'), ('b', 'Biannual'), ('m', 'Monthly'), ('', 'Onetime')], default='', max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('has_link', models.BooleanField(blank=True)),
                ('third_party', models.BooleanField(blank=True)),
                ('active', models.BooleanField(blank=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='reward',
            index_together={('active', 'third_party'), ('has_link', 'third_party')},
        ),
        migrations.AddField(
            model_name='donation',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weblate_web.Reward'),
        ),
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
