# Generated by Django 2.1.4 on 2019-01-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblate_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment',
            field=models.UUIDField(),
        ),
    ]
