# Generated by Django 2.1.3 on 2019-01-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblate_web', '0002_auto_20190102_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='thanks_link',
            field=models.BooleanField(blank=True, db_index=True, default=False),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='reward',
            index_together={('active', 'third_party')},
        ),
    ]
